# Generated by Django 4.2.11 on 2026-01-19 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0004_organization_subscription_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("custom_api", "Custom API"),
                            ("shopify", "Shopify"),
                            ("woocommerce", "WooCommerce"),
                            ("webhook", "Webhook"),
                        ],
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_sources",
                        to="accounts.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomAPISource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_url", models.URLField()),
                (
                    "auth_type",
                    models.CharField(
                        choices=[("none", "None"), ("api_key", "API Key")],
                        default="none",
                        max_length=16,
                    ),
                ),
                (
                    "api_key",
                    models.TextField(
                        blank=True,
                        help_text="Stored encrypted later; plaintext allowed for MVP",
                        null=True,
                    ),
                ),
                (
                    "schema",
                    models.JSONField(
                        help_text="User-defined schema for Playground reasoning"
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_api",
                        to="sources.datasource",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="sources.datasource",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source", "created_at"],
                        name="sources_sou_source__8e3293_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="datasource",
            index=models.Index(
                fields=["organization", "type"], name="sources_dat_organiz_710a9a_idx"
            ),
        ),
    ]
