# Generated by Django 4.2.11 on 2026-01-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customapisource",
            name="auth_type",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("api_key", "API Key"),
                    ("bearer", "earer Token"),
                    ("basic", "Basic Auth"),
                    ("oauth2", "OAuth 2.0"),
                ],
                default="none",
                max_length=16,
            ),
        ),
    ]
