# Generated by Django 4.2.11 on 2026-01-18 13:38

import apps.billing.plans
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_organizationinvite"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="plan",
            field=models.CharField(
                choices=[
                    ("starter", "starter"),
                    ("pro", "pro"),
                    ("enterprise", "enterprise"),
                ],
                default=apps.billing.plans.Plan["STARTER"],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="trial_ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="trial_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
