# Generated by Django 4.2.11 on 2026-01-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_organization_plan_organization_trial_ends_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="subscription_active",
            field=models.BooleanField(default=False),
        ),
    ]
